default_page: 0

variable_defaults:
  title: "Let's play!"
  desc_0: "  Horizon Forbidden West"
#  desc_1: "- Looks like my camera broke :("
  desc_1: ""
  color_0: "#fff6cd26"
  color_1: "#ffac6b26"
  color_2: "#ff563226"
  color_7: "#ff393939"
  sbs: 64
  sbp: 8
  sbx: 1344
  sby: 8
  box_posx: 460
  box_width: 1000
  box_padding: 8
  timer_title: ""
  timer: 0
  timer_hidden: true

elements:
  - name: Soundbank
    type: soundbank
    parameters:
      soundbank_file: "default.omsb"

  - name: Fill Block
    type: block
    disabled: false
    parameters:
      pos_x: 0
      pos_y: 0
      width: 1920
      height: 1080
#      color: "#ff00bb"
      color: "#000000"


  - name: Background Block
    type: block
    parameters:
      pos_x: "$box_posx"
      pos_y: 890
      width: "$box_width"
      height: 170
      color: "#393939"

  - name: Background Image
    type: image
    disabled: true
    parameters:
      pos_x: 0
      pos_y: 870
      filename: title_frame.png

  - name: Title Shadow
    type: text
    parameters:
      pos_x: "$box_posx+$box_padding"
#      pos_x: 35
      pos_y: 875
      width: 960
      height: 120
      size: 90
      bounding_box_pos_x: 20
      bounding_box_pos_y: 870
      bounding_box_width: 1880
      text: "$title"
      font: ../data/fonts/FiraCode-Medium.ttf
      color: "0xff563226"
  - name: Title
    type: text
    parameters:
      pos_x: "$box_posx+$box_padding"
      pos_y: 870
      width: 960
      height: 120
      size: 90
      bounding_box_pos_x: 20
      bounding_box_pos_y: 870
      bounding_box_width: 1880
      text: "$title"
      font: ../data/fonts/FiraCode-Medium.ttf
      color: "0xfff6cd26"

  - name: Description Shadow
    type: text
    parameters:
      pos_x: "$box_posx+$box_padding"
      pos_y: 972
      width: 960
      height: 120
      size: 80
      bounding_box_pos_x: 20
#      bounding_box_pos_y: 870
      bounding_box_width: 1880
      text: "$desc_0"
      font: ../data/fonts/FiraCode-Medium.ttf
      color: "0xff222222"

  - name: Description
    type: text
    parameters:
      pos_x: "$box_posx+$box_padding"
      pos_y: 970
      width: 960
      height: 120
      size: 80
      bounding_box_pos_x: 20
#      bounding_box_pos_y: 870
      bounding_box_width: 1880
      text: "$desc_0"
      font: ../data/fonts/FiraCode-Medium.ttf
      color: "0xffffffff"


  - name: Timer
    type: timer
    disabled: true
    parameters:
      variable: "timer"
      text_variable: "timer_text"
      hide_on_zero: $timer_hidden
      sound_on_zero: TIMER_EXPIRED


  - name: Timer Background Block
    type: block
    disabled: true
    parameters:
      pos_x: 1670
      pos_y: 10
      width: 240
      height: 170
      color: "#000040ff"

  - name: TimerTitleText
    type: text
    disabled: true
    parameters:
      pos_x: 1710
      pos_y: 10
      width: 200
      height: 120
      size: 60
      bounding_box_pos_x: 1710
      bounding_box_width: 200
      text: "$timer_title"
      font: ../data/fonts/FiraCode-Medium.ttf
      color: "0xffffffff"

  - name: TimerText
    type: text
    disabled: true
    hidden: true
    parameters:
      pos_x: 1570
      pos_y: 60
      width: 200
      height: 120
      size: 80
      bounding_box_pos_x: 1690
      bounding_box_width: 200
      text: "$timer_text"
      font: ../data/fonts/FiraCode-Medium.ttf
      color: "0xffffffff"

  - name: Bug anti666 Image
    type: image
    disabled: false
    parameters:
      pos_x: 0
      pos_y: 0
      filename: ../data/bugs/anti666tv-round-150.png


pages:
  - name: Page 0
    elements:
    - name: Page 0 Stripe
      type: block
      disabled: true
      parameters:
        pos_x: 0
        pos_y: 490
        width: 1980
        height: 100
        color: 0xff202080

  - name: Page Soon
    elements:
    - name: Page 1 Stripe
      type: block
      parameters:
        pos_x: 0
        pos_y: 390
        width: 1980
        height: 300
        color: 0xff202080
    - name: Page 1 Text
      type: text
      parameters:
        pos_x: 20
        pos_y: "370+10*sin(3*$time)"
        width: 1980
        height: 300
        size: 280
        bounding_box_pos_x: 20
        bounding_box_pos_y: 390
        bounding_box_width: 1980
        text: "\"Soon...\""
        font: ../data/fonts/FiraCode-Medium.ttf
        color: "0xffffffff"

  - name: Page BRB
    elements:
    - name: Page 2 Stripe
      type: block
      parameters:
        pos_x: 0
        pos_y: "390-140"
        width: 1980
        height: "300+280"
        color: 0xff202080
    - name: Page 2 Text
      type: text
      parameters:
        pos_x: 20
        pos_y: "370+10*sin(3*$time)-140"
        width: 1980
        height: 300
        size: 280
        bounding_box_pos_x: 20
        bounding_box_pos_y: "390-140+50"
        bounding_box_width: 1980
        text: "\"Taking a\""
        font: ../data/fonts/FiraCode-Medium.ttf
        color: "0xffffffff"

    - name: Page 2 Text b
      type: text
      parameters:
        pos_x: 20
        pos_y: "370+10*sin(3*$time)+140"
        width: 1980
        height: 300
        size: 280
        bounding_box_pos_x: 20
        bounding_box_pos_y: "390+140"
        bounding_box_width: 1980
        text: "\"little break!\""
        font: ../data/fonts/FiraCode-Medium.ttf
        color: "0xffffffff"
