default_page: 0

variable_defaults:
  color_0: "#fff6cd26"
  color_1: "#ffac6b26"
  color_2: "#ff563226"
  color_7: "#ff393939"
  sbs: 64
  sbp: 8
  sbx: 1344
  sby: 8
  timer_title: ""
  timer: 0
  timer_hidden: true

elements:
  - name: Soundbank
    type: soundbank
    parameters:
      soundbank_file: "default.omsb"

  - name: Fill Block
    type: block
    disabled: true
    parameters:
      pos_x: 0
      pos_y: 0
      width: 1920
      height: 1080
        # color: "#ff00bb"
      color: "black"


  - name: Background Block
    type: block
    disabled: true
    parameters:
      pos_x: 20
      pos_y: 890
      width: 1200
      height: 170
        # color: "#393939"
      color: "black"

  - name: Background Image
    type: image
    disabled: true
    parameters:
      pos_x: 0
      pos_y: 870
      filename: title_frame.png

  - name: Title
    type: text
    parameters:
      pos_x: 30
      pos_y: 870
      width: 960
      height: 120
      size: 90
      bounding_box_pos_x: 20
      bounding_box_pos_y: 870
      bounding_box_width: 1880
      bounding_box_height: 240
      text: "text_lines_from_file(0,1,\"title_desc.txt\")"
      font: ../data/fonts/FiraCode-Medium.ttf
      color: "0xfff6cd26"
      glow_color: "0xff563226"
      glow_size: 2

  - name: Description
    type: text
    parameters:
      pos_x: 30
      pos_y: 970
      width: 960
      height: 120
      size: 40
      bounding_box_pos_x: 20
#      bounding_box_pos_y: 870
      bounding_box_width: 1880
      text: "text_lines_from_file(1,2,\"title_desc.txt\")"
      font: ../data/fonts/FiraCode-Medium.ttf
      color: "0xffffffff"
      shadow_color: "0xff444444"
      shadow_offset_x: 2
      shadow_offset_y: 2

  - name: Description
    type: text
    disabled: true
    parameters:
      pos_x: 30
      pos_y: 1010
      width: 960
      height: 120
      size: 40
      bounding_box_pos_x: 20
#      bounding_box_pos_y: 870
      bounding_box_width: 1880
      text: "text_lines_from_file(2,1,\"title_desc.txt\")"
      font: ../data/fonts/FiraCode-Medium.ttf
      color: "0xffffffff"
      shadow_color: "0xff444444"
      shadow_offset_x: 2
      shadow_offset_y: 2


  - name: Timer
    type: timer
    disabled: true
    parameters:
      variable: "timer"
      text_variable: "timer_text"
#      hide_on_zero: $timer_hidden
      sound_on_zero: TIMER_EXPIRED
      initial_value: 10
      repeat: false

  - name: Timer Background Block
    type: block
    disabled: true
    parameters:
      pos_x: 1670
      pos_y: 10
      width: 240
      height: 170
      color: "#000040ff"

  - name: TimerTitleText
    type: text
    disabled: true
    parameters:
      pos_x: 1710
      pos_y: 10
      width: 200
      height: 120
      size: 60
      bounding_box_pos_x: 1710
      bounding_box_width: 200
      text: "$timer_title"
      font: ../data/fonts/FiraCode-Medium.ttf
      color: "0xffffffff"

  - name: TimerText
    type: text
    hidden: true
    disabled: true
    parameters:
      pos_x: 1570
      pos_y: 60
      width: 200
      height: 120
      size: 80
      bounding_box_pos_x: 1690
      bounding_box_width: 200
      text: "$timer_text"
      font: ../data/fonts/FiraCode-Medium.ttf
      color: "0xffffffff"

  - name: Bug
    type: image
    hidden: false
    disabled: false
    parameters:
      pos_x: 20
      pos_y: 20
      filename: ../data/bugs/anti666tv-round-150.png

pages:
  - name: Page 0
    elements:
    - name: Page 0 Stripe
      type: block
      disabled: true
      parameters:
        pos_x: 0
        pos_y: 490
        width: 1980
        height: 100
        color: 0xff202080

  - name: Page 1
    elements:
    - name: Page 1 Stripe
      type: block
      parameters:
        pos_x: 0
        pos_y: 390
        width: 1980
        height: 300
        color: 0xff202080
    - name: Page 1 Text
      type: text
      parameters:
        pos_x: 20
        pos_y: 390
        width: 1980
        height: 300
        size: 280
        bounding_box_pos_x: 20
        bounding_box_pos_y: 390
        bounding_box_width: 1980
        text: "\"Soon...\""
        font: ../data/fonts/FiraCode-Medium.ttf
        color: "0xffffffff"
        glow_color: "0xa08080a0"
        glow_size: 2

