variable_defaults:
  title: "Apple Spring Event"
  desc_0: "Just watching the event,"
  desc_1: "and doing some cheval config on the side"
  color_0: "#f6cd26"
  color_1: "#ac6b26"
  color_2: "#563226"
  color_7: "#393939"
elements:
  - name: Background Block
    type: block
    parameters:
      pos_x: 20
      pos_y: 890
      width: 1200
      height: 170
      color: "#393939"
  - name: Title Shadow
    type: text
    parameters:
      pos_x: 35
      pos_y: 875
      width: 960
      height: 120
      size: 90
      bounding_box_pos_x: 20
      bounding_box_pos_y: 870
      bounding_box_width: 1880
      text: "$title"
      font: ../data/fonts/FiraCode-Medium.ttf
      color: "0xff563226"
  - name: Title
    type: text
    parameters:
      pos_x: 30
      pos_y: 870
      width: 960
      height: 120
      size: 90
      bounding_box_pos_x: 20
      bounding_box_pos_y: 870
      bounding_box_width: 1880
      text: "$title"
      font: ../data/fonts/FiraCode-Medium.ttf
      color: "0xfff6cd26"

  - name: Description
    type: text
    parameters:
      pos_x: 30
      pos_y: 970
      width: 960
      height: 120
      size: 40
      bounding_box_pos_x: 20
#      bounding_box_pos_y: 870
      bounding_box_width: 1880
      text: "$desc_0"
      font: ../data/fonts/FiraCode-Medium.ttf
      color: "0xffac6b26"
  - name: Description
    type: text
    parameters:
      pos_x: 30
      pos_y: 1010
      width: 960
      height: 120
      size: 40
      bounding_box_pos_x: 20
#      bounding_box_pos_y: 870
      bounding_box_width: 1880
      text: "$desc_1"
      font: ../data/fonts/FiraCode-Medium.ttf
      color: "0xffac6b26"
